### ISSUE TITLE
WebView2 crashes after downloading anything

### ISSUE THREAD

**Issue by frank-liu-toronto** [MicrosoftEdge/WebView2Feedback#1723]
**Description**
WebView2 crashes after downloading anything

**Version**
SDK: 1.0.961.33
Runtime: Stable Channel, Version 93.0.961.38 (Offcial Build) (64-bit)
Framework: WinForms with .net framework 4.8 (I also tried .net framework 4.6.2)
OS: Windows 10

**Repro Steps**
- Create a win form project with VS community, choose .net framework 4.8
- Install webview2 nuget package (latest stable). Current latest stable version is 1.0.961.33
- Drag webview2 onto the default form
- Set Source to http://www.bing.com
- Run Debug in Visual Studio 
- Search "download 7zip" in the bing page
- Choose the offical 7-zip.org link in the search result which popups another "browser window."
- Click on any download link to download a version of 7zip.
- After the download, close the popup "browser window".
- Observe the parent default windows form crashes and the following error is reported:

System.InvalidOperationException
  HResult=0x80131509
  Message=CoreWebView2 members cannot be accessed after the WebView2 control is disposed.
  Source=Microsoft.Web.WebView2.Core
  StackTrace:
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
   at Microsoft.Web.WebView2.WinForms.WebView2.OnGotFocus(EventArgs e)
   at System.Windows.Forms.Control.InvokeGotFocus(Control toInvoke, EventArgs e)
   at System.Windows.Forms.Control.WmSetFocus(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at Microsoft.Web.WebView2.WinForms.WebView2.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Inner Exception 1:
COMException: The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)

**Screenshots**
![image](https://user-images.githubusercontent.com/20232640/132706180-7098bf66-46a4-4eca-8780-7b04457a7059.png)

**Additional context**

[AB#35907166](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/35907166)

**Comment by jarno9981** [comment]
@frank-liu-toronto   same for my youtube.com just goes black and then crashes

**Comment by jarno9981** [comment]
@champnic    major  bug when downloading stuff

**Comment by champnic** [comment]
Thanks for the bug report! I've added it to our backlog and we'll take a look right away. 

@jarno9981 Are you also seeing this on the latest 1.0.961.33 nuget package?
Does it still happen if using a different runtime version (like Canary) or a different SDK package?

**Comment by jarno9981** [comment]
@champnic yes the latest release from the nuget

**Comment by RichardSteele** [comment]
@champnic Win32 is affected as well: (https://github.com/MicrosoftEdge/WebView2Feedback/issues/1712#issuecomment-914953918). This bug doesn't appear in Canary channel (95.0.1010.0).

**Comment by Deepanghoshs** [comment]
@champnic, Can we have any release date for the fix or can you please give an approximate date for this fix, since we are going for release after this fix on webview2

**Comment by champnic** [comment]
The fix is getting checked in today, and will be flowing to the channels shortly afterwards.

**Comment by vickiez** [comment]
The fix is now available in Canary 96.0.1023.0. Can you verify that this fixes the issue for you? 
Thanks!

**Comment by Deepanghoshs** [comment]
@vickiez we are using Microsoft.Web.WebView2 version 1.0.961.33,  Can you please confirm, when are we getting  the above mentioned updated

**Comment by jarno9981** [comment]
@Deepanghoshs  latest pre-release 1.0.1018-prerelease

works fine now with edge & edge beta it will not crash anymore for my then

**Comment by Deepanghoshs** [comment]
@jarno9981 I have updated to the pre-release 1.0.1018-prerelease in the sample project and our releasing project. But both showing the same error as previously shown. I am afraid the latest fix did not worked for my workflow. I have attached the sample project in [Ticket with Sample Project](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1734)

**Comment by Dabraham6** [comment]
Will the fix for this issue just require updating the WebView2 runtime? We are currently using version 93.0.961.52 of the runtime, will it be in the next version whenever that is released?

**Comment by Dabraham6** [comment]
Just FYI I tested using the Canary Edge version and our issue is resolved in that

**Comment by vickiez** [comment]
Thanks for testing - yes, the fix will come with a Runtime update soon

**Comment by Deepanghoshs** [comment]
I am trying to test the sample mentioned by @frank-liu-toronto. 

My Environment Details 
Windows 10 pro with latest updates Version	10.0.19043 Build 19043
MS Edge WEBview2 Runtime 94.0.992.31
Microsoft Edge Version 96.0.1028.0 (Official build) dev (64-bit)

But still getting the crashing error.  Can you provide link to download the patch containing the fix

**Comment by champnic** [comment]
@Deepanghoshs You can have your app pickup the Dev runtime using these instructions:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel

Thanks!

**Comment by fvanheeswijk** [comment]
Why is this fix not being actively pushed to the stable channel? In my opinion this is a serious bug and needs to be addressed as soon as possible, we cannot afford to wait until canary propagates to dev, beta and then stable.

**Comment by champnic** [comment]
@fvanheeswijk The fix was pushed to stable and should be available in versions 94.0.992.29+ (in the current stable). Are you still seeing this issue in runtimes newer than this?

**Comment by fvanheeswijk** [comment]
So we have finally managed to reproduce the (new) download bug, we have the following source code:

```
using System;
using System.Threading;
using System.Windows.Forms;

using Microsoft.Web.WebView2.WinForms;

namespace WebView2BugDownload
{
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(CreateNewForm());
        }

        private static Form CreateNewForm()
        {
            var form = new Form
            {
                Size = new System.Drawing.Size(800, 600)
            };

            var webView2 = new WebView2
            {
                Dock = DockStyle.Fill,
                Source = new Uri(@"https://paste.ee/p/1qgu7")
            };

            webView2.CoreWebView2InitializationCompleted += (sender, e) =>
            {
                webView2.CoreWebView2.ProcessFailed += (sender2, e2) =>
                {
                    MessageBox.Show($"Crashed: {e2.ExitCode} / {e2.ProcessDescription} / {e2.ProcessFailedKind} / {e2.Reason}");
                };
            };

            form.Controls.Add(webView2);

            var button = new Button
            {
                Dock = DockStyle.Bottom,
                Text = "Open new form"
            };
            button.Click += (sender, e) =>
            {
                var thread = new Thread(() =>
                {
                    var newForm = CreateNewForm();
                    newForm.Shown += (sender2, e2) => newForm.Activate();
                    newForm.ShowDialog();
                });
                thread.SetApartmentState(ApartmentState.STA);
                thread.Start();
            };

            form.Controls.Add(button);

            return form;
        }
    }
}
```

When you keep repeating the following steps after opening the application it will eventually crash (between two and five repetitions necessary usually):

1. Click 'Open new form'.
2. Press the 'Download' **icon** on the paste.ee website.
3. Close the form.

The message box shown is as follows for me:
`Crashed: 1 / / BrowserProcessExited / Unexpected`

@champnic Could you please take another look at this issue? This is the only big issue remaining that is preventing our application from going into production.

**Comment by champnic** [comment]
@fvanheeswijk We are currently looking into this. Thanks for the repro steps! @vickiez FYI

**Comment by gabrielrvd** [comment]
Hi, I had same problem with WPF and 97.0.1060.0 fix it. Thank you!!! When release this version rollout in production?

**Comment by champnic** [comment]
By default this will be in the 97 release, sometime around the beginning of January. I realize this is a long time, so we'll see about getting it backported to 96 and shipped in mid-November. Thanks!

**Comment by fvanheeswijk** [comment]
@champnic Unfortunately this issue is still not fixed for us, it still reproduces with the test project listed on https://github.com/MicrosoftEdge/WebView2Feedback/issues/1723#issuecomment-946636408.

I tested it with the latest Microsoft.WebView2 version 1.0.1056-prerelease and with Canary build 97.0.1060.0.
Now it gives the following output when it crashes: 
`Crashed: -1073741819 /  /  BrowserProcessExited / Unexpected`

**Comment by vickiez** [comment]
Hi @fvanheeswijk , do you have a crash dump you can share? We have not been able to repro with the test project you provided.

**Comment by fvanheeswijk** [comment]
@vickiez Thank you for checking again, it should still reproduce. However I think I have found the issue! It only seems to reproduce when you do **not** close the Downloads popup in the right top before closing the form.

**Comment by r-cass** [comment]
Maybe i'm wrong but it seems to be related to window management as @fvanheeswijk wrote for this download popup. I've reported the same issue elsewhere (i did not notice this one) https://github.com/MicrosoftEdge/WebView2Feedback/issues/1777 . In this reported issue, the developer encounters issue by using devtools, the stack trace seems to be the same. @vickiez I provided a crash dump https://github.com/MicrosoftEdge/WebView2Feedback/issues/1777#issuecomment-946516634 .

**Comment by vickiez** [comment]
@fvanheeswijk @r-cass thanks for the info! Just to double check, do you get the same dump as the one in #1777 with the latest Canary? We made a change to how the popup is closed that resolved this kind of crash for others

**Comment by fvanheeswijk** [comment]
@vickiez It still reproduces for us with NuGet package 1.0.1056-prerelease and user agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4691.0 Safari/537.36 Edg/97.0.1071.0 (so we should be in the prerelease mode).

However we didn't realize that crashdumps are being written automatically, this is the crashdump we got: [ec89732c-e4c9-44cb-a442-d8b1a0468cce.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7519283/ec89732c-e4c9-44cb-a442-d8b1a0468cce.zip)

It looks like an access violation has occurred within the browser process.

**Comment by r-cass** [comment]
@vickiez sorry I found this opened issue a bit late, so the crash dump I provided on #1777 was a bit outdated. 
However, I tried with with runtime 98.0.1077.0, the issue seems to be fixed, thanks!

**Comment by kolozsaron** [comment]
SDK: 1.0.1056-prerelease
Runtime: Canary 98.0.1081.0
...seems to work for me as well. Thanks!

**Comment by champnic** [comment]
Thanks everyone for verifying! I'm going to close this issue as fixed, but if you do run into a downloads related crash again, please include stack, crash dump (if available), and what runtime you are using and we'll take a look. Thanks!

**Comment by fvanheeswijk** [comment]
Thank you! With the latest Canary 98.0.1084.0 it seems to be fixed indeed (haven't tested other 98.0.x builds).

Can this fix be applied on the current stable release as well?
