### ISSUE TITLE
Spell check suggestion text is not available in ContextMenuRequested event

### ISSUE THREAD

**Issue by q71114** [MicrosoftEdge/WebView2Feedback#2340]
**Description**
`CoreWebView2ContextMenuRequestedEventArgs.MenuItems` for `CoreWebView2.ContextMenuRequested` event contain list of commands with `spellcheck` name but there's no way to get the actual suggestion text.

**Version**
SDK: 1.0.1189-prerelease
Runtime: 100.0.1185.29
Framework: WPF
OS: Win11

**Repro Steps**
1. Add event handler to `CoreWebView2.ContextMenuRequested`
2. Start the application
3. Right click on a misspelled word
4. There are `spellcheck` commands in `CoreWebView2ContextMenuRequestedEventArgs.MenuItems`  but there's no suggestions available for any of them. Setting their `CommandId` as `SelectedCommandId` works properly as the misspelled word will be corrected.

**Screenshots**
![image](https://user-images.githubusercontent.com/8770144/161941471-425e68eb-aa34-4620-ac31-30f97b6984f9.png)

**Additional context**
Without this information it's not possible for us to build a custom context menu with spell check suggestions.

**Comment by champnic** [comment]
Thanks for the bug report @q71114 - I've added this to our backlog.

**Comment by sayalivk** [comment]
I am also facing same issue in latest release build 1.0.1185.39

**Comment by MarkIngramUK** [comment]
@carlosbet , your "curious behaviour" sounds like it could be #3142

**Comment by srwei** [comment]
When right clicking for the context menu on the misspelled word text, what are you seeing? Are there blank strings in the menu items or is there the placeholder (i.e. "Getting suggestions")?

**Comment by RendijsSmukulis** [comment]
@srwei Following @q71114 's repro steps, we're seeing blank labels in the `CoreWebView2ContextMenuRequestedEventArgs.MenuItems`:

```
+++> Caught CoreWebView2ContextMenuRequestedEventArgs with menu items:
 +++> label: '', name: 'spellcheck', kind: 'Command'
 +++> label: '', name: 'spellcheck', kind: 'Command'
 +++> label: '', name: 'spellcheck', kind: 'Command'
 +++> label: '', name: 'other', kind: 'Separator'
 +++> label: 'Cu&t', name: 'cut', kind: 'Command'
 +++> label: '&Copy', name: 'copy', kind: 'Command'
 +++> label: '&Paste', name: 'paste', kind: 'Command'
 +++> label: 'P&aste as plain text', name: 'pasteAndMatchStyle', kind: 'Command'
 +++> label: '&Share', name: 'share', kind: 'Command'
 +++> label: '&Web capture', name: 'webCapture', kind: 'Command'
 +++> label: '', name: 'other', kind: 'Separator'
 +++> label: 'I&nspect', name: 'inspectElement', kind: 'Command'
```

**Comment by fvanheeswijk** [comment]
When can we expect this issue to be resolved? Without it we cannot fully integrate WebView2 in our application and this bug has been open for more than a year already...

**Comment by Flaflo** [comment]
Also would like to know the state of this issue right now. @srwei

**Comment by pdolanjski** [comment]
The spell checking APIs are currently completely broken. Because of this bug a custom context menu cannot be used (since you're left with blank labels so the spelling options cannot be displayed for users), but even if you attempt to use a non-custom context menu, because of [issue 3142](https://github.com/MicrosoftEdge/WebView2Feedback/issues/3142) the spelling suggestions just never appear.
cc @nishitha-burman @liminzhu

**Comment by nishitha-burman** [comment]
Hello,

A fix has been checked into Canary 123+. Can you please check if this issue is resolved for you? 

Thanks!

**Comment by q71114** [comment]
Hi @nishitha-burman,

Thanks for letting us know, unfortunately it still doesn't seem to work. 
Here is the test I conducted using `Scenario` > `Custom Context Menu` in WebView2Samples.
You can see that the spell check suggestions are still blank:

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/8770144/df6a8de0-3cb7-4c34-bb43-68f4b014d83c)

**Comment by nishitha-burman** [comment]
Hello,

Can you please try with Runtime version 123.0.2376.0? 

Thanks!

**Comment by dianaqu** [comment]
Also note that if you switch to customized context menu live. You gonna need to refresh once to resolve the blank issue

**Comment by dianaqu** [comment]
Hi @q71114 
I did some quick debugging this morning and we found a bug on using customized context menu on the fly, the related object will not be initialized. But a workaround is to start up Webview2 with enabled customized context menu and set up handlers. That way, spellcheck will work as expected, Thanks @nishitha-burman for verify that route!

**Comment by fvanheeswijk** [comment]
Unfortunately custom context menu items still do not have the spellcheck text available, I don't exactly know what you mean by your latest suggestion @dianaqu but can we expect a fix soon?

I'm also especially interested as the 1.0.2277.86 SDK update mentions "Ensured that the spellcheck language matches put_Language programmatically. The customized context menu is also updated with correct spellchecks. (Runtime-only)" which seems to be this issue, so it will be fixed in Stable 121.0.2277.86+ as well?

**Comment by q71114** [comment]
> a workaround is to start up Webview2 with enabled customized context menu and set up handlers

@dianaqu, I'm so sorry, but it's still not clear to me what is the workaround here. Do you mind sharing a code sample that I can try out?

**Comment by dianaqu** [comment]
@nishitha-burman Do you mind sharing what you tried to get it working?

**Comment by nirbil** [comment]
Was there some breaking change around this recently?
I'm using WebView2 under UWP with recent dev channel and the entire spell checking functionality is now completely missing.
It wasn't working properly in the first place (had to resort to my own spell checker to fill in the blanks in the context menu, using a custom context menu), but now it's completely missing, no red line under misspelled text, no relevant option in the context menu.

**Comment by dianaqu** [comment]
@nirbil yes and no. We have shipped couple fixes to ensure spellcheck works for different languages. And we noticed a bug that without using put_Language to set language to en-US, spellcheck will get disabled. The current workaround is to set language. I'm working on fixing the issue.

**Comment by nirbil** [comment]
> @nirbil yes and no. We have shipped couple fixes to ensure spellcheck works for different languages. And we noticed a bug that without using put_Language to set language to en-US, spellcheck will get disabled. The current workaround is to set language. I'm working on fixing the issue.

I ensured that the default language is set to 'en-US' in the app manifest.
I suspect something was broken along the way at least on UWP as the spell check is now disabled and it used to (somewhat) work.
Should I open a new bug?

**Comment by dianaqu** [comment]
What version of WebView2 runtime are you using? And what channel?

**Comment by nirbil** [comment]
Latest version - 1.0.2277.86.
Checked it in both dev and standard channels.

**Comment by dianaqu** [comment]
121.0.2277.112 have all fixes we cherry pick. Could you update and try that?

**Comment by nirbil** [comment]
That's the current stable release channel version.
I checked it, spell checking doesn't work.

**Comment by q71114** [comment]
> @nishitha-burman Do you mind sharing what you tried to get it working?

@dianaqu @nishitha-burman Is there any update on this? I'd love to try out the aforementioned workaround if you could share it with me.

**Comment by nishitha-burman** [comment]
In the Sample app code I set `m_allowCustomMenus` to true (it is false by default). You can find this in SettingsComponent.h. And now am seeing spellcheck suggestions. Does this work for you?

**Comment by q71114** [comment]
> m_allowCustomMenus

@nishitha-burman Thanks for that. I only ever tried the WPF integration sample app (`WebView2WpfBrowser`) because that one resembles more to what we try to achieve and I couldn't find something similar to what you wrote. Does that mean at the moment this feature (spell check suggestion using custom menu) won't work with the WPF integration?

**Comment by nirbil** [comment]
> Was there some breaking change around this recently? I'm using WebView2 under UWP with recent dev channel and the entire spell checking functionality is now completely missing. It wasn't working properly in the first place (had to resort to my own spell checker to fill in the blanks in the context menu, using a custom context menu), but now it's completely missing, no red line under misspelled text, no relevant option in the context menu.

Should I start a separate regression bug for WinUI2/UWP?

**Comment by dianaqu** [comment]
> > m_allowCustomMenus
> 
> @nishitha-burman Thanks for that. I only ever tried the WPF integration sample app (`WebView2WpfBrowser`) because that one resembles more to what we try to achieve and I couldn't find something similar to what you wrote. Does that mean at the moment this feature (spell check suggestion using custom menu) won't work with the WPF integration?

In WPF you can do something like this
`webView.CoreWebView2.ContextMenuRequested += WebView_ContextMenuRequested;`

**Comment by dianaqu** [comment]
Quick questions to folks. Are you trying to paint your own context menu or just trying to remove item from browser context menu

**Comment by q71114** [comment]
> Are you trying to paint your own context menu or just trying to remove item from browser context menu. 

We do the former.

> If you are painting your own context menu, spellcheck is not yet supported. We have a backlog item to add new API to support retrieving spellcheck suggestions. But if you don't paint your own context menu, rather just remove/add item from the existing browser context menu. Spellcheck is supported in this case.

Just to clarify this means this bug is still not fixed as you have a separate backlog item for it. The one you fixed is this issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3142

**Comment by dianaqu** [comment]
> 
> Just to clarify this means this bug is still not fixed as you have a separate backlog item for it. The one you fixed is this issue: #3142

Yes. It's a separate issue from #3142. We fixed the spellcheck for using browser context menu since that don't require any SDK change. for painting your own context menu, that require a bit more change

**Comment by fvanheeswijk** [comment]
> > Just to clarify this means this bug is still not fixed as you have a separate backlog item for it. The one you fixed is this issue: #3142
> 
> Yes. It's a separate issue from #3142. We fixed the spellcheck for using browser context menu since that don't require any SDK change. for painting your own context menu, that require a bit more change

Is there any news on when this will be fixed?

**Comment by nirdil** [comment]
> > Just to clarify this means this bug is still not fixed as you have a separate backlog item for it. The one you fixed is this issue: #3142
> 
> Yes. It's a separate issue from #3142. We fixed the spellcheck for using browser context menu since that don't require any SDK change. for painting your own context menu, that require a bit more change

Is this currently worked on its in the backlog?
I don't think that fixing the spellcheck on a custom context menu (which most companies probably use) requires any SDK changes. The item's label attribute just need to be filled with the suggestion rather then be left blank as it currently is.

**Comment by fvanheeswijk** [comment]
Is there any news on this yet? We are still missing it for custom context menus after more than three years.
