### ISSUE TITLE
[Problem/Bug]: Save as PDF via Print \ui

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#4225]
### What happened?

Never had issue before.

Print using "Save as PDF" on the Print dialog.

Ends up showing a small download window (like before) where it does a download count in Kb (never did that before) to 0. Never finishes. the PDF is corrupt and unusable. It is only 744 kb!

This has been stable for months! 

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

120.0.2210.61

### SDK Version

2088.41

### Framework

Win32

### Operating System

Windows 11

### OS Version

22621.2715

### Repro steps

Try to us the "Save as PDF" via Print UI.

Microsoft Edge is the same.

### Repros in Edge Browser

Yes

### Regression

Don't know

**Comment by ajtruckle** [comment]
I can do a direct save as PDF via the PDF api. That works as before. but not the print UI route.

**Comment by ajtruckle** [comment]
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7985331/322cd142-8338-4b6e-9439-b143cf6c9b66)

I have asked other users to test and it no longer functions. This is critical for my software.

**Comment by ajtruckle** [comment]
@champnic Hi. This one I raised today is frustrating g. It is changed behaviour and no longer functional in webview2 or Edge for me. Why?

**Comment by victorhuangwq** [comment]
I was able to replicate this bug on the Edge Browser as well. We are tracking it in our backlog.

**Comment by xylolink** [comment]
Hi, is a debug planned ? It's a major issue, my customers can't produce any pdf from edge and they can't use any other browser.

**Comment by victorhuangwq** [comment]
The fix is planned. Based on current estimates, the fix should be in the stable runtime by Friday. I will confirm on this thread once the fix is in stable.

**Comment by monica-ch** [comment]
Until the fixes reaches stable, can you/customers print the PDF document using `Microsoft Print to PDF` printer from the print dialog on windows.

**Comment by ajtruckle** [comment]
@monica-ch Yeah. Fortunately I have a dedicated Export feature too that directly saves to PDF which still works. But, point taken about using the alternate printer driver.

**Comment by xylolink** [comment]
> Until the fixes reaches stable, can you/customers print the PDF document using `Microsoft Print to PDF` printer from the print dialog on windows.

Yes but it's forced in A5 format due to a former bug in Edge and Chrome.

**Comment by Leightym** [comment]
Another issue with using the Microsoft Print to PDF printer is the save as dialog is not using the title of the document as the default filename. This breaks our line of business app.

**Comment by monica-ch** [comment]
Sorry to hear this, the fix should start to roll out on machines from 12/14 and will be available on all machines soon..

**Comment by Leightym** [comment]
Thank you for the update. Timing is everything. We leave for holiday vacation next week and won't be back in the office until Jan 2nd.  I need to know my employees will be able to keep on working while we're gone.

**Comment by bouncy99** [comment]
any update on this?  it is the 14th, and i don't see an update, or anything listed on the release notes to suggest an update has been published. https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel Version 120.0.2210.61 as the latest.    As the previous posted advised, with christmas, time is critical as support teams reduce as annual leave kicks in for the holiday season.  we need to know that this is fixed.

**Comment by MAD-King** [comment]
Still the same issue with version 120.0.2210.61 (Official build) (64-bit), I am not able to "print as PDF" on the context menu. I am switching to Chrome. Edge has way too many bugs right now. Chrome works fine with print as PDF.

**Comment by Leightym** [comment]
> Still the same issue with version 120.0.2210.61 (Official build) (64-bit), I am not able to "print as PDF" on the context menu. I am switching to Chrome. Edge has way too many bugs right now. Chrome works fine with print as PDF.

I wish that were possible for us as this is not just an issue with the standalone browser. I have 2 applications that use the WebView2 control. Since Google has nothing similar we're stuck waiting for this to get fixed.

**Comment by MAD-King** [comment]
> > Still the same issue with version 120.0.2210.61 (Official build) (64-bit), I am not able to "print as PDF" on the context menu. I am switching to Chrome. Edge has way too many bugs right now. Chrome works fine with print as PDF.
> 
> I wish that were possible for us as this is not just an issue with the standalone browser. I have 2 applications that use the WebView2 control. Since Google has nothing similar we're stuck waiting for this to get fixed.

I am not able to wait until MS decides when to fix it. They lost me and my business to Google Chrome.

**Comment by monica-ch** [comment]
We have backported the fix and should start rolling out today and will take 48-52 hours to reach all customers. I'll update the thread with the stable patch version# soon.

**Comment by xstaindx** [comment]
Do you know when this will be avaiable through WSUS/Microsoft Update/Windows Update release channels for Enterprise Deployment?  Is your 48 hour estimate including that? Thank you.

**Comment by Leightym** [comment]
v120.0.2210.77 just arrived, and I've confirmed it does fix the issue. Thanks, team, for getting this done so quickly!

**Comment by xylolink** [comment]
Same here, v120.0.2210.77 is installed and pdf printer is working well. Thanks for your responsiveness !

**Comment by ajtruckle** [comment]
@monica-ch Edge is fine now thanks. But my issue remains as I originally raised concerning WebView2 itself. When will that be fixed?

**Comment by fabiorocha** [comment]
@ajtruckle WebView2 updates rollout over a 48-hour window, which is slower than the browser rollout window. This is because WebView2 has less usage in early release channels (Canary/Dev/Beta), so its Stable rollout is slower for us to be able identify issues early and have enough time to react and pause rollout, if needed. Let us know if you still see the issue in the 120.0.2210.77 Webview2 runtime.

**Comment by fabiorocha** [comment]
@xstaindx apologies I missed your question earlier. The release should be available in the wsus catalog within hours of release, let me know if you can't see it.

**Comment by xstaindx** [comment]
> @xstaindx apologies I missed your question earlier. The release should be available in the wsus catalog within hours of release, let me know if you can't see it.

I was able to grab them via WSUS Sync overnight, tonight. thank you for this big effort! :)

**Comment by ajtruckle** [comment]
@xstaindx never heard of WSUS! 😀

**Comment by ajtruckle** [comment]
@fabiorocha I tried manually running the install from here:

https://www.catalog.update.microsoft.com/Search.aspx?q=Webview2

The x64 bit one at the top and all I get is "Installation Error".

**Comment by ajtruckle** [comment]
I manually updated WebView2 using the approach explained here:

https://github.com/MicrosoftEdge/WebView2Feedback/issues/3371#issuecomment-1500917825

All good now.

**Comment by monica-ch** [comment]
Closing the issue as it is fixed in 120.0.2210.77+ and validated.
